name: CI

on:
  push:
    paths: 
    - 'src/**'
    - 'bin/**'
    - 'test/**'
  pull_request:
    paths: 
    - 'src/**'
    - 'bin/**'
    - 'test/**'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm test


